### Numpy Assignment 
-------------

Consider the below code to answer further questions: 

    import numpy as np
    list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
    array_list = np.array(object = list_)

####  Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [50]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [51]:
list_

['1', '2', '3', '4', '5']

In [52]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [53]:
## Yes there is a difference between the list_ & array_list

## list_ --> list type datatype

## array_list --> ndarray type data type.

In [54]:

print("The variable list_ is of Datatype :",type(list_))


The variable list_ is of Datatype : <class 'list'>


In [57]:
print("The variable array_list is of Datatype :",type(array_list))

The variable array_list is of Datatype : <class 'numpy.ndarray'>


------------

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.


In [58]:
for i in range(len(list_)):
    print("The datatype of the element - {} at the index {} of list_  is : {}" .format(list_[i],i,type(list_[i] )))
    
    ## list_ --> each element is of datatype - Str

The datatype of the element - 1 at the index 0 of list_  is : <class 'str'>
The datatype of the element - 2 at the index 1 of list_  is : <class 'str'>
The datatype of the element - 3 at the index 2 of list_  is : <class 'str'>
The datatype of the element - 4 at the index 3 of list_  is : <class 'str'>
The datatype of the element - 5 at the index 4 of list_  is : <class 'str'>


In [49]:
for i in range(len(array_list)):
    print("The datatype of the element - {} at the index {} of array_list  is : {}" .format(array_list[i],i,array_list[i].dtype))
    
    ## array_list --> each element is of datatype - numpy.str

The datatype of the element - 1 at the index 0 of array_list  is : int64
The datatype of the element - 2 at the index 1 of array_list  is : int64
The datatype of the element - 3 at the index 2 of array_list  is : int64
The datatype of the element - 4 at the index 3 of array_list  is : int64
The datatype of the element - 5 at the index 4 of array_list  is : int64


----------------------

Q3. Considering the following changes in the variable, array_list:

    array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.



In [59]:
list_
## The elements in the list_

['1', '2', '3', '4', '5']

In [60]:

array_list = np.array(object = list_, dtype = int)
array_list
## the elements in array_list

array([1, 2, 3, 4, 5])

In [61]:
# Yes there is difference  in the datatype of the elements in the 2 variables.

## list_ ---> the elements are String Datatype

## array_list --> the elements are integer datatype

In [62]:
for i in range(len(list_)):
    print("The datatype of the element - {} at the index {} of list_  is : {}" .format(list_[i],i,type(list_[i] )))
    

The datatype of the element - 1 at the index 0 of list_  is : <class 'str'>
The datatype of the element - 2 at the index 1 of list_  is : <class 'str'>
The datatype of the element - 3 at the index 2 of list_  is : <class 'str'>
The datatype of the element - 4 at the index 3 of list_  is : <class 'str'>
The datatype of the element - 5 at the index 4 of list_  is : <class 'str'>


In [63]:
for i in range(len(array_list)):
    print("The datatype of the element - {} at the index {} of array_list  is : {}" .format(array_list[i],i,array_list[i].dtype))
    
    ## all the elements are - numpy.int64

The datatype of the element - 1 at the index 0 of array_list  is : int64
The datatype of the element - 2 at the index 1 of array_list  is : int64
The datatype of the element - 3 at the index 2 of array_list  is : int64
The datatype of the element - 4 at the index 3 of array_list  is : int64
The datatype of the element - 5 at the index 4 of array_list  is : int64


-----------------------


#### Consider the below code to answer further questions:

    import numpy as np
    num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
    num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
    
    (i) shape
    (ii) size



In [64]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [66]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
## (i) shape
num_array.shape

## (2,3) --> rows,calumns
## the num_array has 2 rows and 3 columns


(2, 3)

In [68]:
## (ii) size

num_array.size

## it gives the total number of elements in the arrray
## row * Column
## 2*3 ==> 6 elements

6

----------------------------------

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [72]:
array_q5 = np.zeros((3,3))
array_q5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
array_q5.shape # the row * column = 3 x 3

(3, 3)

In [74]:
array_q5.size # the total element sin array = 3*3 = 9

9

----------------------

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [76]:
import numpy.matlib as num

# first we need to import the matlib module

In [80]:

matrix_q6 = num.eye(5,5)  # function used to create a identity matrix

matrix_q6 

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

------------------------------